services:
  pytorch-env:
    command: bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['1', '3', '5', '7']
            count: all
            capabilities: [gpu]
    shm_size: '16gb'
    # user: "${UID}:${GID}"
    image: ${USER}/${IMAGE_LABEL}
    container_name: ${CONTAINER_NAME}
    hostname: docker-container
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${USER_NAME}
        - UID=${UID}
        - GID=${GID}
        - PASSWORD=${USER_NAME}
        - WORKDIR=${WORKDIR_CONTAINER}
      context: .
      shm_size: '16gb'
      dockerfile: Dockerfile
    tty: true
    # volumes:
    #   - "${WORKDIR_LOCAL}:${WORKDIR_CONTAINER}"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      # - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
      - "${WORKDIR_LOCAL}:${WORKDIR_CONTAINER}"
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
